# Generated by Django 5.0.4 on 2025-11-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media')),
                ('tavsif', models.TextField(blank=True)),
                ('haqida', models.CharField(max_length=200)),
            ],
        ),
    ]
