# Generated by Django 5.0.4 on 2025-11-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loyiha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='yaratilgan_vaqt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
