# Generated by Django 5.0.4 on 2025-11-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loyiha', '0002_main_yaratilgan_vaqt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Main', 'verbose_name_plural': 'Mening Narsalarim'},
        ),
    ]
